version: '3.6'

services:
    mongo:
        image: mongo:4
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - ./_setup/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
            - ./_setup/mongodb/replica.key:/data/replica.key
            - mongo_data:/data/db
        command: --replSet rs0 --bind_ip_all --keyFile /data/replica.key

    redis:
        image: redis
        ports:
            - '6379:6379'

    mongo-express:
        image: mongo-express
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

    redis-commander:
        image: rediscommander/redis-commander
        ports:
            - '8082:8081'
        environment:
            REDIS_HOST: redis

volumes:
    mongo_data:
