version: '3.6'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/monitool-public:cached
    command: sleep infinity

  mongo:
    image: mongo:4
    network_mode: service:devcontainer
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./_setup/mongodb/replica.key:/data/replica.key
      - mongo_data:/data/db
    command: --replSet rs0 --bind_ip_all --keyFile /data/replica.key

  redis:
    image: redis
    network_mode: service:devcontainer

  mongo-express:
    image: mongo-express
    network_mode: service:devcontainer
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@localhost:27017/

  redis-commander:
    image: rediscommander/redis-commander
    network_mode: service:devcontainer
    environment:
      REDIS_HOST: redis
      PORT: 8082

volumes:
  mongo_data:
