version: '3.6'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/monitool-public:cached
    command: sleep infinity

  mongo:
    image: mongo:5
    network_mode: service:devcontainer
    volumes:
      - mongo_data:/data/db
    command: --replSet rs0 --bind_ip_all

  redis:
    image: redis
    network_mode: service:devcontainer

  redis-commander:
    image: rediscommander/redis-commander
    network_mode: service:devcontainer
    environment:
      REDIS_HOST: redis
      PORT: 8082

volumes:
  mongo_data:
