version: '3.6'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/monitool-public:cached
    command: sleep infinity

  mongo:
    image: mongo:5
    network_mode: service:devcontainer
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    command: --replSet rs0 --bind_ip_all

  redis:
    image: redis
    network_mode: service:devcontainer

  mongo-express:
    image: mongo-express
    network_mode: service:devcontainer
    depends_on:
      - mongo
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/

  redis-commander:
    image: rediscommander/redis-commander
    network_mode: service:devcontainer
    environment:
      REDIS_HOST: redis
      PORT: 8082

volumes:
  mongo_data:
